theme                  : "minimal-mistakes-jekyll"
# remote_theme           : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en-US"
title                    : "Site Title"
title_separator          : "-"
subtitle                 : "o0o.st" # site tagline that appears below site title in masthead
name                     : "Your Name"
description              : "An amazing website."
url                      : "https://o0o.st/" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : "" # the subpath of your site, e.g. "/blog"
repository               : "Terrorboy/o0o.st" # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
